/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __lcmFrame_lcmFrame_hpp__
#define __lcmFrame_lcmFrame_hpp__

#include <lcm/lcm_coretypes.h>


namespace lcmFrame
{

class lcmFrame
{
    public:
        int16_t    ImGray[480][640];

        double     timestamp;

        float      mk[3][3];

        float      mDistCoef[4][1];

        float      mbf;

        float      mThDepth;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "lcmFrame"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int lcmFrame::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmFrame::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lcmFrame::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t lcmFrame::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* lcmFrame::getTypeName()
{
    return "lcmFrame";
}

int lcmFrame::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    for (int a0 = 0; a0 < 480; a0++) {
        tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->ImGray[a0][0], 640);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 3; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->mk[a0][0], 3);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < 4; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->mDistCoef[a0][0], 1);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->mbf, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->mThDepth, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmFrame::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    for (int a0 = 0; a0 < 480; a0++) {
        tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->ImGray[a0][0], 640);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 3; a0++) {
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->mk[a0][0], 3);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < 4; a0++) {
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->mDistCoef[a0][0], 1);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->mbf, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->mThDepth, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmFrame::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += 480 * __int16_t_encoded_array_size(NULL, 640);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += 3 * __float_encoded_array_size(NULL, 3);
    enc_size += 4 * __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t lcmFrame::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0xab6dda8099255ddcLL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
