/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __lcmDrawKeyFrame_lcmDrawGraph_hpp__
#define __lcmDrawKeyFrame_lcmDrawGraph_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include "lcmDrawKeyFrame/lcmDrawCovGraphVector.hpp"
#include "lcmDrawKeyFrame/lcmDrawSpanningTree.hpp"
#include "lcmDrawKeyFrame/lcmDrawLoopVector.hpp"

namespace lcmDrawKeyFrame
{

class lcmDrawGraph
{
    public:
        int32_t    num_CovGraphVector;

        std::vector< lcmDrawKeyFrame::lcmDrawCovGraphVector > VectorCovGraphVector;

        int32_t    num_SpTree;

        std::vector< lcmDrawKeyFrame::lcmDrawSpanningTree > VectorSpanningTree;

        int32_t    num_LoopVector;

        std::vector< lcmDrawKeyFrame::lcmDrawLoopVector > VectorLoopVector;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "lcmDrawGraph"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int lcmDrawGraph::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmDrawGraph::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lcmDrawGraph::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t lcmDrawGraph::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* lcmDrawGraph::getTypeName()
{
    return "lcmDrawGraph";
}

int lcmDrawGraph::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_CovGraphVector, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_CovGraphVector; a0++) {
        tlen = this->VectorCovGraphVector[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_SpTree, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_SpTree; a0++) {
        tlen = this->VectorSpanningTree[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_LoopVector, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_LoopVector; a0++) {
        tlen = this->VectorLoopVector[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int lcmDrawGraph::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_CovGraphVector, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->VectorCovGraphVector.resize(this->num_CovGraphVector);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->num_CovGraphVector; a0++) {
        tlen = this->VectorCovGraphVector[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_SpTree, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->VectorSpanningTree.resize(this->num_SpTree);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->num_SpTree; a0++) {
        tlen = this->VectorSpanningTree[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_LoopVector, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->VectorLoopVector.resize(this->num_LoopVector);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->num_LoopVector; a0++) {
        tlen = this->VectorLoopVector[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int lcmDrawGraph::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_CovGraphVector; a0++) {
        enc_size += this->VectorCovGraphVector[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_SpTree; a0++) {
        enc_size += this->VectorSpanningTree[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_LoopVector; a0++) {
        enc_size += this->VectorLoopVector[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

uint64_t lcmDrawGraph::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == lcmDrawGraph::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, lcmDrawGraph::getHash };

    uint64_t hash = 0xec3895261e938aa9LL +
         lcmDrawKeyFrame::lcmDrawCovGraphVector::_computeHash(&cp) +
         lcmDrawKeyFrame::lcmDrawSpanningTree::_computeHash(&cp) +
         lcmDrawKeyFrame::lcmDrawLoopVector::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
